import { db } from "../../firebase-config.js";
import {collection, addDoc } from "firebase/firestore";

// Data to be added
// Assuming this is your list of user data objects
// const usersData = [
//   { school_name: "Hilltop school", school_id: "92004", school_logo_url: "https://png.pngtree.com/png-vector/20230415/ourmid/pngtree-school-logo-design-template-vector-png-image_6705854.png" ,school_address: "101 Hill Ave, Hilltop" },
//     { school_name: "Lakeside Middle School", school_id: "28005", school_logo_url: "https://png.pngtree.com/png-vector/20230415/ourmid/pngtree-school-logo-design-template-vector-png-image_6705854.png" ,school_address: "202 Lakeview Dr, Lakeside" },
//     { school_name: "Maplewood High School", school_id: "39006", school_logo_url: "https://png.pngtree.com/png-vector/20230415/ourmid/pngtree-school-logo-design-template-vector-png-image_6705854.png" ,school_address: "303 Maple Rd, Maplewood" },
//     { school_name: "Valley Forge Academy", school_id: "47009", school_logo_url: "https://png.pngtree.com/png-vector/20230415/ourmid/pngtree-school-logo-design-template-vector-png-image_6705854.png" ,school_address: "606 Forge Rd, Valley" }
// ];

const usersData = [{'SKU': 58165585,
  'product_name': 'School Uniform 42',
  'product_size': 'XS',
  'school_name': 'Riverdale Academy',
  'class': "1",
  'gender': 'male',
  'price': 1000,
  'quantity': 5,
  'school_id': 36002,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 90179386,
  'product_name': 'School Uniform 21',
  'product_size': 'XL',
  'school_name': 'Maplewood High School',
  'class': "8",
  'gender': 'male',
  'price': 2000,
  'quantity': 3,
  'school_id': 39006,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 69776123,
  'product_name': 'School Uniform 5',
  'product_size': 'M',
  'school_name': 'Lakeside Middle School',
  'class': "4",
  'gender': 'male',
  'price': 1500,
  'quantity': 5,
  'school_id': 28005,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 83896265,
  'product_name': 'School Uniform 32',
  'product_size': 'M',
  'school_name': 'Sunnydale School',
  'class': "4",
  'gender': 'male',
  'price': 1200,
  'quantity': 6,
  'school_id': 19003,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 34796771,
  'product_name': 'School Uniform 33',
  'product_size': 'XL',
  'school_name': 'Riverdale Academy',
  'class': "4",
  'gender': 'female',
  'price': 1700,
  'quantity': 6,
  'school_id': 36002,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 52514408,
  'product_name': 'School Uniform 44',
  'product_size': 'S',
  'school_name': 'Riverdale Academy',
  'class': "9",
  'gender': 'female',
  'price': 2300,
  'quantity': 4,
  'school_id': 36002,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 17193600,
  'product_name': 'School Uniform 43',
  'product_size': 'XS',
  'school_name': 'Maplewood High School',
  'class': "3",
  'gender': 'male',
  'price': 2900,
  'quantity': 2,
  'school_id': 39006,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 21487143,
  'product_name': 'School Uniform 23',
  'product_size': 'M',
  'school_name': 'Lakeside Middle School',
  'class': "10",
  'gender': 'female',
  'price': 2300,
  'quantity': 0,
  'school_id': 28005,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 70455432,
  'product_name': 'School Uniform 23',
  'product_size': 'XL',
  'school_name': 'Sunnydale School',
  'class': "3",
  'gender': 'female',
  'price': 1700,
  'quantity': 1,
  'school_id': 19003,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 63580234,
  'product_name': 'School Uniform 14',
  'product_size': 'M',
  'school_name': 'Hilltop school',
  'class': "2",
  'gender': 'female',
  'price': 2500,
  'quantity': 1,
  'school_id': 92004,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 84191453,
  'product_name': 'School Uniform 2',
  'product_size': 'S',
  'school_name': 'Riverdale Academy',
  'class': "4",
  'gender': 'male',
  'price': 3000,
  'quantity': 0,
  'school_id': 36002,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 67745971,
  'product_name': 'School Uniform 23',
  'product_size': 'XS',
  'school_name': 'Maplewood High School',
  'class': "10",
  'gender': 'female',
  'price': 3100,
  'quantity': 8,
  'school_id': 39006,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 52158213,
  'product_name': 'School Uniform 21',
  'product_size': 'XL',
  'school_name': 'Sunnydale School',
  'class': "2",
  'gender': 'male',
  'price': 3800,
  'quantity': 7,
  'school_id': 19003,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 62050411,
  'product_name': 'School Uniform 43',
  'product_size': 'XL',
  'school_name': 'Riverdale Academy',
  'class': "7",
  'gender': 'male',
  'price': 3400,
  'quantity': 5,
  'school_id': 36002,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 91633641,
  'product_name': 'School Uniform 38',
  'product_size': 'M',
  'school_name': 'Maplewood High School',
  'class': "5",
  'gender': 'female',
  'price': 3300,
  'quantity': 7,
  'school_id': 39006,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 71833075,
  'product_name': 'School Uniform 39',
  'product_size': 'M',
  'school_name': 'Lakeside Middle School',
  'class': "3",
  'gender': 'male',
  'price': 4100,
  'quantity': 0,
  'school_id': 28005,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 54973559,
  'product_name': 'School Uniform 50',
  'product_size': 'M',
  'school_name': 'Riverdale Academy',
  'class': "5",
  'gender': 'male',
  'price': 4800,
  'quantity': 8,
  'school_id': 36002,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 18624361,
  'product_name': 'School Uniform 44',
  'product_size': 'XS',
  'school_name': 'Greenwood High',
  'class': "6",
  'gender': 'female',
  'price': 4300,
  'quantity': 7,
  'school_id': 89001,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 64808181,
  'product_name': 'School Uniform 32',
  'product_size': 'L',
  'school_name': 'Maplewood High School',
  'class': "5",
  'gender': 'female',
  'price': 4500,
  'quantity': 1,
  'school_id': 39006,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 24484995,
  'product_name': 'School Uniform 8',
  'product_size': 'XL',
  'school_name': 'Lakeside Middle School',
  'class': "2",
  'gender': 'female',
  'price': 4700,
  'quantity': 2,
  'school_id': 28005,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 84159515,
  'product_name': 'School Uniform 48',
  'product_size': 'XL',
  'school_name': 'Hilltop school',
  'class': "2",
  'gender': 'male',
  'price': 5200,
  'quantity': 1,
  'school_id': 92004,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 62226656,
  'product_name': 'School Uniform 21',
  'product_size': 'S',
  'school_name': 'Maplewood High School',
  'class': "7",
  'gender': 'male',
  'price': 5900,
  'quantity': 7,
  'school_id': 39006,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 15676317,
  'product_name': 'School Uniform 49',
  'product_size': 'XS',
  'school_name': 'Greenwood High',
  'class': "5",
  'gender': 'male',
  'price': 5300,
  'quantity': 7,
  'school_id': 89001,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 14600983,
  'product_name': 'School Uniform 21',
  'product_size': 'XL',
  'school_name': 'Sunnydale School',
  'class': "7",
  'gender': 'female',
  'price': 5200,
  'quantity': 2,
  'school_id': 19003,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 71696028,
  'product_name': 'School Uniform 21',
  'product_size': 'M',
  'school_name': 'Greenwood High',
  'class': "10",
  'gender': 'male',
  'price': 5800,
  'quantity': 9,
  'school_id': 89001,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 22570115,
  'product_name': 'School Uniform 21',
  'product_size': 'M',
  'school_name': 'Valley Forge Academy',
  'class': "9",
  'gender': 'female',
  'price': 6200,
  'quantity': 4,
  'school_id': 47009,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 42586645,
  'product_name': 'School Uniform 39',
  'product_size': 'L',
  'school_name': 'Greenwood High',
  'class': "1",
  'gender': 'male',
  'price': 6700,
  'quantity': 8,
  'school_id': 89001,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 53046150,
  'product_name': 'School Uniform 34',
  'product_size': 'S',
  'school_name': 'Maplewood High School',
  'class': "7",
  'gender': 'male',
  'price': 6500,
  'quantity': 6,
  'school_id': 39006,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 51677930,
  'product_name': 'School Uniform 27',
  'product_size': 'XS',
  'school_name': 'Valley Forge Academy',
  'class': "10",
  'gender': 'female',
  'price': 6600,
  'quantity': 0,
  'school_id': 47009,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'},
 {'SKU': 40390262,
  'product_name': 'School Uniform 35',
  'product_size': 'M',
  'school_name': 'Lakeside Middle School',
  'class': "10",
  'gender': 'male',
  'price': 6900,
  'quantity': 0,
  'school_id': 28005,
  'image_url': 'https://www.huber-online.com/daisy_website_files/_processed_/8/0/csm_no-image_d5c4ab1322.jpg'}]

async function addUsers(usersData) {
  for (const userData of usersData) {
    try {
      const docRef = await addDoc(collection(db, "products"), userData);
      console.log("Document written with ID: ", docRef.id);
    } catch (e) {
      console.error("Error adding document: ", e);
    }
  }
}

// Call the function to add users
addUsers(usersData);


// const db = getFirestore(app);

// const data  = [
//     { school_name: "Greenwood High", school_id: "89001", school_logo_url: "https://png.pngtree.com/png-vector/20230415/ourmid/pngtree-school-logo-design-template-vector-png-image_6705854.png" ,school_address: "123 Forest Rd, Greenwood" },
//     { school_name: "Riverside Academy", school_id: "36002", school_logo_url: "https://png.pngtree.com/png-vector/20230415/ourmid/pngtree-school-logo-design-template-vector-png-image_6705854.png" ,school_address: "456 River Bend, Riverside" },
//     { school_name: "Sunnydale Elementary", school_id: "19003", school_logo_url: "https://png.pngtree.com/png-vector/20230415/ourmid/pngtree-school-logo-design-template-vector-png-image_6705854.png" ,school_address: "789 Sunny St, Sunnydale" },
//     { school_name: "Hilltop school", school_id: "92004", school_logo_url: "https://png.pngtree.com/png-vector/20230415/ourmid/pngtree-school-logo-design-template-vector-png-image_6705854.png" ,school_address: "101 Hill Ave, Hilltop" },
//     { school_name: "Lakeside Middle School", school_id: "28005", school_logo_url: "https://png.pngtree.com/png-vector/20230415/ourmid/pngtree-school-logo-design-template-vector-png-image_6705854.png" ,school_address: "202 Lakeview Dr, Lakeside" },
//     { school_name: "Maplewood High School", school_id: "39006", school_logo_url: "https://png.pngtree.com/png-vector/20230415/ourmid/pngtree-school-logo-design-template-vector-png-image_6705854.png" ,school_address: "303 Maple Rd, Maplewood" },
//     { school_name: "Valley Forge Academy", school_id: "47009", school_logo_url: "https://png.pngtree.com/png-vector/20230415/ourmid/pngtree-school-logo-design-template-vector-png-image_6705854.png" ,school_address: "606 Forge Rd, Valley" }
//     // ... more data
// ];



